version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.14

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: cd frontend && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - '9e:37:c3:94:46:c6:d7:e4:da:0e:b7:27:14:e9:aa:4e'
    - checkout
    - run:
        name: Push Main to Production
        command: |
          git push https://github.com/Just-Hosam/WannaBitly main:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
