DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  short_url VARCHAR(255) NOT NULL,
  long_url VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL DEFAULT ''
)