DROP TABLE IF EXISTS clicks CASCADE;

CREATE TABLE clicks (
  id SERIAL PRIMARY KEY NOT NULL,
  url_id INTEGER REFERENCES urls(id) ON DELETE CASCADE,
  click_timestamp TIMESTAMP NOT NULL,
  city VARCHAR(144) NOT NULL,
  country VARCHAR(144) NOT NULL
)